### ISSUE TITLE
uninitialized constant ActionView::CompiledTemplates::FoundationPagination

### ISSUE THREAD

**Issue by MrSkinny** [acrogenesis/will_paginate-foundation#5]
I'm getting the error **uninitialized constant ActionView::CompiledTemplates::FoundationPagination**
when using:

`<%= will_paginate @collection, renderer: FoundationPagination::Rails %>`

Gems used:

```
foundation-rails 5.4.0.0
will_paginate 3.0.7
will_paginate-foundation 5.3.4
```

Any thoughts?

**Comment by hungdh0x5e** [comment]
+1
Can u tell me how to `precompile assets`?
