### ISSUE TITLE
Support for Foundation 6?

### ISSUE THREAD

**Issue by patricklindsay** [acrogenesis/will_paginate-foundation#7]
Any plans to support Foundation 6?

**Comment by acrogenesis** [comment]
Any PR is more than welcome :)

**Comment by cyrusstoller** [comment]
This seems to work already. Thanks for maintaining this gem.

**Comment by andey** [comment]
Please update the documentation of Foundation 6 works. 

Right now, im using dsandstrom/will_paginate-foundation on the 'foundation-6' branch. 

I rather use a gem, than referencing github on my Gemfile.

**Comment by acrogenesis** [comment]
@andey Are you getting any errors? All commits on dsandstrom/will_paginate-foundation#foundation-6 are merged here.

**Comment by andey** [comment]
@acrogenesis I haven't tried to be honest

I was just trying to suggest that if this project supports foundation 6 it should indicate it on the readme. 

I'll try the gem now.
