### ISSUE TITLE
Fixnum is deprecated in Ruby 2.4

### ISSUE THREAD

**Issue by dsandstrom** [acrogenesis/will_paginate-foundation#8]
```
.../will_paginate-foundation-6.2.0/lib/foundation_pagination/foundation_renderer.rb:10: warning: constant ::Fixnum is deprecated
```

https://bugs.ruby-lang.org/issues/12005

Need to change to Bignum or support both Bignum and Fixnum.

**Comment by acrogenesis** [comment]
Can you help with a PR?

**Comment by dsandstrom** [comment]
I was misinformed, both Bignum and Fixnum are deprecated.  Their methods were moved to Integer.
